/* ============================================
   World of Sea Battle - Map Data
   ============================================
   
   HOW TO CUSTOMIZE:
   -----------------
   1. PORTS: edit the `ports` array
      - type: 'k' = small, 'n' = normal, 'f' = fortified, 'p' = pirate
   
   2. LIGHTHOUSES: edit the `lighthouses` array
   
   3. POIs: edit the `pois` array
      - type values: island, coal, copper, farm, iron, resin, rum, water, wood, printshop, altar, fort
      - outsideMap: true for approximate locations in the endless sea
   
   ============================================ */

const MAP_WIDTH = 1863;
const MAP_HEIGHT = 1551;

// =============================================================================
// MAP SCALE — adjust this to match your in-game measurements
// Measure a known distance in-game (with Ctrl ruler) and adjust this value.
// Default: 97.867 pixels = 1000 in-game distance units
// =============================================================================
const PIXELS_PER_NM = 97.867;
const ISLAND_RADIUS_NM = 7; // radius circle around personal island in nm

// =============================================================================
// LOCALIZATION (DE/EN)
// Port names have German translations (name_de field in port data)
// =============================================================================
const i18n = {
  en: {
    title: 'World of Sea Battle',
    subtitle: 'Interactive Map by Vi5E',
    metaDescription: 'Portable interactive map for World of Sea Battle with ports, lighthouses, production sites, personal islands, and tracking tools.',
    loadingMap: 'Loading map...',
    toggleSidebar: 'Toggle sidebar',
    toggleDarkModeTitle: 'Toggle dark mode (D)',
    dark: 'Dark',
    legend: 'Legend',
    measure: 'Measure',
    clearMeasure: 'Clear All',
    searchPlaceholder: 'Search ports, islands, resources...',
    mapLayers: 'Map Layers',
    ports: 'Ports',
    lighthouses: 'Lighthouses',
    fastTravel: 'Fast Travel Routes',
    savedRoutes: 'Saved Routes',
    routeAnimation: 'Line Animations',
    islands: 'Personal Islands',
    production: 'Production Sites',
    altars: 'Altars',
    forts: 'Forts',
    pvpCircle: 'PVP Circle Border',
    customMarkers: 'Free Markers',
    myIsland: 'My Locations',
    islandRadius: 'Island Radius (7nm)',
    legendTitle: 'Icon Legend',
    iconLegend: 'Icon Legend',
    keyboardShortcuts: 'Keyboard Shortcuts',
    imprint: 'Imprint',
    imprintIntro: 'This website is an unofficial fan project.',
    imprintRights: 'All rights to World of Sea Battle and all associated names, logos, assets, trademarks, and game content remain with their respective rights holders, especially Thera Interactive as developer and publisher.',
    imprintAffiliation: 'I am not affiliated with, endorsed by, sponsored by, or otherwise connected to Thera Interactive.',
    toggleLayers: 'Toggle layers',
    toggleLegend: 'Toggle legend',
    search: 'Search',
    darkMode: 'Dark Mode',
    mapActions: 'Map actions',
    addMarkerLabel: 'Add marker',
    shortcutRightClick: 'Right-click',
    exportMarkers: 'Export Markers',
    importMarkers: 'Import Markers',
    addMarkerDialog: 'Add Custom Marker',
    markerLabelPlaceholder: 'Marker label...',
    islandNamePlaceholder: 'Name...',
    cancel: 'Cancel',
    save: 'Save',
    addMarker: 'Add Marker',
    addMarkerCtx: 'Add Marker',
    copyCoords: 'Copy Coordinates',
    copyCoordsSuccess: 'Copied: {coords}',
    markAsMyIsland: 'Mark as mine',
    unmarkMyIsland: 'Unmark',
    distance: 'Distance',
    normalPort: 'Normal Port',
    smallPort: 'Small Port',
    fortifiedPort: 'Fortified Port',
    piratePort: 'Pirate Port',
    outsideMap: 'Outside Map (approx.)',
    position: 'Position',
    type: 'Type',
    holdCtrl: 'Hold Ctrl to measure',
    nm: 'nm',
    lighthouse: 'Lighthouse',
    personalIsland: 'Personal Island',
    altar: 'Altar',
    fort: 'Fort',
    coal: 'Coal',
    copper: 'Copper',
    farm: 'Farm',
    iron: 'Iron',
    resin: 'Resin',
    rum: 'Rum',
    water: 'Water',
    wood: 'Wood',
    printshop: 'Printshop',
    outsideNote: 'Red outline = outside known map (approximate)',
    searchTypePort: 'Port',
    searchTypeIsland: 'Island',
    searchTypeProduction: 'Resource',
    searchTypeAltar: 'Altar',
    searchTypeFort: 'Fort',
    rename: 'Rename',
    delete: 'Delete',
    customMarkerDefault: 'Custom Marker',
    noPersonalMarks: 'No personal marks',
    noFilteredPersonalMarks: 'No markers for the active filters',
    statusLegend: 'Status',
    notSet: 'Not set',
    noWorkshop: 'No workshop',
    noProduction: 'No production',
    noWarehouse: 'No warehouse',
    zone: 'Zone',
    nearestPort: 'Nearest port',
    unknownZone: 'Unknown zone',
    knownIslandWorkshops: 'Known island workshops',
    knownIslandProductions: 'Known island productions',
    workshopZoneHint: 'Zone-based options for {zone}',
    languageChangedEnglish: 'Language: English',
    languageChangedGerman: 'Language: Deutsch',
    collapseAll: '▲ Collapse All',
    expandAll: '▼ Expand All',
    warehouse: 'Warehouse',
    workshop: 'Workshop',
    workshops: 'Workshops',
    productionLabel: 'Production',
    setWarehouse: 'Set as warehouse',
    removeWarehouse: 'Remove warehouse',
    selectWorkshops: 'Select workshops (max 2)',
    selectWorkshop: 'Select workshop',
    selectProduction: 'Select production',
    none: 'None',
    ws_plank: 'Beam Workshop',
    ws_weaving: 'Weaving Workshop',
    ws_bronze: 'Bronze Foundry',
    ws_plate: 'Plate Workshop',
    ws_bulkhead: 'Bulkhead Workshop',
    ws_provision: 'Provision Production',
    prod_beer: 'Beer',
    prod_grain: 'Grain',
    prod_supplies: 'Supplies',
    prod_sugar: 'Sugar',
    pw_plank: 'Beam',
    pw_bronze: 'Bronze',
    pw_plate: 'Plate',
    pw_canvas: 'Canvas',
    pw_bulkhead: 'Bulkhead',
    pw_foundry: 'Foundry',
    warehouseSetIn: 'Warehouse set in {name}',
    warehouseRemovedFrom: 'Warehouse removed from {name}',
    maxPortWorkshops: 'Maximum 2 workshops per port!',
    portWorkshopUpdated: 'Workshop updated',
    workshopSelected: 'Workshop: {name}',
    workshopRemoved: 'Workshop removed',
    productionSelected: 'Production: {name}',
    productionRemoved: 'Production removed',
    limitReachedIslands: 'You can only mark up to {count} personal islands!',
    limitReachedMines: 'You can only mark up to {count} mines!',
    limitReachedPrintshops: 'You can only mark up to {count} printshops!',
    markedAsMine: '{name} marked as mine!',
    markRemoved: 'Mark removed',
    nameYourIsland: 'Name your island',
    defaultPersonalMarker: 'My Marker',
    markerSaved: '"{name}" saved!',
    customMarkerAdded: 'Marker "{name}" added',
    customMarkerDeleted: 'Marker "{name}" deleted',
    customMarkersImported: '{count} markers imported',
    invalidJsonFile: 'Invalid JSON file',
    mapInitError: 'Map startup error: {message}',
    deleteMeasurePoint: 'Delete',
    importSuccess: 'Import successful'
  },
  de: {
    title: 'World of Sea Battle',
    subtitle: 'Interaktive Karte by Vi5E',
    metaDescription: 'Portable interaktive Karte für World of Sea Battle mit Häfen, Leuchttürmen, Produktionspunkten, persönlichen Inseln und Tracking-Werkzeugen.',
    loadingMap: 'Karte wird geladen...',
    toggleSidebar: 'Seitenleiste umschalten',
    toggleDarkModeTitle: 'Dunkelmodus umschalten (D)',
    dark: 'Dunkel',
    legend: 'Legende',
    measure: 'Messen',
    clearMeasure: 'Alle löschen',
    searchPlaceholder: 'Häfen, Inseln, Ressourcen suchen...',
    mapLayers: 'Kartenebenen',
    ports: 'Häfen',
    lighthouses: 'Leuchttürme',
    fastTravel: 'Schnellreiserouten',
    savedRoutes: 'Gespeicherte Routen',
    routeAnimation: 'Linienanimationen',
    islands: 'Persönliche Inseln',
    production: 'Produktionsstätten',
    altars: 'Altäre',
    forts: 'Festungen',
    pvpCircle: 'PVP-Kreisgrenze',
    customMarkers: 'Freie Marker',
    myIsland: 'Meine Standorte',
    islandRadius: 'Inselradius (7nm)',
    legendTitle: 'Symbollegende',
    iconLegend: 'Symbollegende',
    keyboardShortcuts: 'Tastenkürzel',
    imprint: 'Impressum',
    imprintIntro: 'Diese Website ist ein inoffizielles Fanprojekt.',
    imprintRights: 'Alle Rechte an World of Sea Battle sowie an allen zugehörigen Namen, Logos, Grafiken, Marken und Spielinhalten liegen bei den jeweiligen Rechtsinhabern, insbesondere bei Thera Interactive als Entwickler und Publisher.',
    imprintAffiliation: 'Ich bin weder mit Thera Interactive verbunden noch von Thera Interactive unterstützt, gesponsert oder autorisiert.',
    toggleLayers: 'Ebenen umschalten',
    toggleLegend: 'Legende umschalten',
    search: 'Suchen',
    darkMode: 'Dunkelmodus',
    mapActions: 'Kartenaktionen',
    addMarkerLabel: 'Marker setzen',
    shortcutRightClick: 'Rechtsklick',
    exportMarkers: 'Marker exportieren',
    importMarkers: 'Marker importieren',
    addMarkerDialog: 'Eigenen Marker setzen',
    markerLabelPlaceholder: 'Markerbeschriftung...',
    islandNamePlaceholder: 'Name...',
    cancel: 'Abbrechen',
    save: 'Speichern',
    addMarker: 'Marker setzen',
    addMarkerCtx: 'Marker setzen',
    copyCoords: 'Koordinaten kopieren',
    copyCoordsSuccess: 'Kopiert: {coords}',
    markAsMyIsland: 'Als meine markieren',
    unmarkMyIsland: 'Markierung entfernen',
    distance: 'Entfernung',
    normalPort: 'Normaler Hafen',
    smallPort: 'Kleiner Hafen',
    fortifiedPort: 'Befestigter Hafen',
    piratePort: 'Piratenhafen',
    outsideMap: 'Außerhalb der Karte (ca.)',
    position: 'Position',
    type: 'Typ',
    holdCtrl: 'Strg halten zum Messen',
    nm: 'sm',
    lighthouse: 'Leuchtturm',
    personalIsland: 'Persönliche Insel',
    altar: 'Altar',
    fort: 'Festung',
    coal: 'Kohle',
    copper: 'Kupfer',
    farm: 'Farm',
    iron: 'Eisen',
    resin: 'Harz',
    rum: 'Rum',
    water: 'Wasser',
    wood: 'Holz',
    printshop: 'Druckerei',
    outsideNote: 'Roter Rahmen = außerhalb der bekannten Karte (ungefähr)',
    searchTypePort: 'Hafen',
    searchTypeIsland: 'Insel',
    searchTypeProduction: 'Ressource',
    searchTypeAltar: 'Altar',
    searchTypeFort: 'Festung',
    rename: 'Umbenennen',
    delete: 'Löschen',
    customMarkerDefault: 'Eigener Marker',
    noPersonalMarks: 'Keine Markierungen',
    noFilteredPersonalMarks: 'Keine Markierungen für die aktiven Filter',
    statusLegend: 'Status',
    notSet: 'Nicht gesetzt',
    noWorkshop: 'Keine Werkstatt',
    noProduction: 'Keine Produktion',
    noWarehouse: 'Kein Lager',
    zone: 'Region',
    nearestPort: 'Nächster Hafen',
    unknownZone: 'Unbekannte Region',
    knownIslandWorkshops: 'Bekannte Insel-Werkstätten',
    knownIslandProductions: 'Bekannte Insel-Produktionen',
    workshopZoneHint: 'Regionale Optionen für {zone}',
    languageChangedEnglish: 'Sprache: Englisch',
    languageChangedGerman: 'Sprache: Deutsch',
    collapseAll: '▲ Alle einklappen',
    expandAll: '▼ Alle ausklappen',
    warehouse: 'Lager',
    workshop: 'Werkstatt',
    workshops: 'Werkstätten',
    productionLabel: 'Produktion',
    setWarehouse: 'Als Lager markieren',
    removeWarehouse: 'Lager entfernen',
    selectWorkshops: 'Werkstätten wählen (max 2)',
    selectWorkshop: 'Werkstatt wählen',
    selectProduction: 'Produktion wählen',
    none: 'Keine',
    ws_plank: 'Balkenwerkstatt',
    ws_weaving: 'Weberei',
    ws_bronze: 'Bronzeschmelze',
    ws_plate: 'Plattenwerkstatt',
    ws_bulkhead: 'Schottwerkstatt',
    ws_provision: 'Proviantproduktion',
    prod_beer: 'Bier',
    prod_grain: 'Getreide',
    prod_supplies: 'Vorräte',
    prod_sugar: 'Zucker',
    pw_plank: 'Balken',
    pw_bronze: 'Bronze',
    pw_plate: 'Platte',
    pw_canvas: 'Segeltuch',
    pw_bulkhead: 'Schott',
    pw_foundry: 'Gießerei',
    warehouseSetIn: 'Lager in {name} gesetzt',
    warehouseRemovedFrom: 'Lager in {name} entfernt',
    maxPortWorkshops: 'Maximal 2 Werkstätten pro Hafen!',
    portWorkshopUpdated: 'Werkstatt aktualisiert',
    workshopSelected: 'Werkstatt: {name}',
    workshopRemoved: 'Werkstatt entfernt',
    productionSelected: 'Produktion: {name}',
    productionRemoved: 'Produktion entfernt',
    limitReachedIslands: 'Du kannst nur maximal {count} persönliche Inseln markieren!',
    limitReachedMines: 'Du kannst nur maximal {count} Minen markieren!',
    limitReachedPrintshops: 'Du kannst nur maximal {count} Druckereien markieren!',
    markedAsMine: '{name} als meine markiert!',
    markRemoved: 'Markierung entfernt',
    nameYourIsland: 'Name für deine Insel',
    defaultPersonalMarker: 'Mein Marker',
    markerSaved: '"{name}" gespeichert!',
    customMarkerAdded: 'Marker "{name}" hinzugefügt',
    customMarkerDeleted: 'Marker "{name}" gelöscht',
    customMarkersImported: '{count} Marker importiert',
    invalidJsonFile: 'Ungültige JSON-Datei',
    mapInitError: 'Fehler beim Kartenstart: {message}',
    deleteMeasurePoint: 'Löschen',
    importSuccess: 'Import erfolgreich'
  }
};
// =============================================================================
// PORT DATA  (name = EN, name_de = DE in-game translation)
// =============================================================================
const ports = [
  { name: "Assab",              name_de: "Assab",              x: 97,   y: 1211, type: "k" },
  { name: "Cursed City",        name_de: "Verfluchte Stadt",   x: 101,  y: 636,  type: "n" },
  { name: "Al-Khalif",          name_de: "Al-Khalif",          x: 110,  y: 1393, type: "k" },
  { name: "Nisogora",           name_de: "Nisogora",           x: 166,  y: 434,  type: "n" },
  { name: "Nordberg",           name_de: "Nordberg",           x: 217,  y: 301,  type: "f" },
  { name: "West Bastion",       name_de: "Westbastion",        x: 214,  y: 818,  type: "n" },
  { name: "Sharhat",            name_de: "Sharhat",            x: 290,  y: 1105, type: "k" },
  { name: "Oneg",               name_de: "Oneg",               x: 341,  y: 121,  type: "n" },
  { name: "Naabad Stronghold",  name_de: "Festung Naabad",     x: 403,  y: 676,  type: "p" },
  { name: "Gelbion",            name_de: "Gelbion",            x: 483,  y: 342,  type: "n" },
  { name: "Masadora",           name_de: "Masadora",           x: 499,  y: 829,  type: "n" },
  { name: "Devios",             name_de: "Devios",             x: 540,  y: 1177, type: "n" },
  { name: "El Tigre",           name_de: "El Tigre",           x: 552,  y: 1364, type: "f" },
  { name: "Surako",             name_de: "Surako",             x: 553,  y: 529,  type: "f" },
  { name: "Corsa-Nois Bay",     name_de: "Corsa-Nois-Bucht",   x: 672,  y: 102,  type: "p" },
  { name: "Bridgetown",         name_de: "Bridgetown",         x: 730,  y: 836,  type: "n" },
  { name: "San Cristobel",      name_de: "San Cristobel",      x: 751,  y: 1350, type: "n" },
  { name: "Charleston",         name_de: "Charleston",         x: 763,  y: 986,  type: "n" },
  { name: "Nevis",              name_de: "Nevis",              x: 826,  y: 539,  type: "n" },
  { name: "Pirate City",        name_de: "Piratenstadt",       x: 843,  y: 1419, type: "p" },
  { name: "Everston",           name_de: "Everston",           x: 867,  y: 232,  type: "n" },
  { name: "Laguna Blanco",      name_de: "Laguna Blanco",      x: 975,  y: 969,  type: "n" },
  { name: "Aruba",              name_de: "Aruba",              x: 1083, y: 354,  type: "n" },
  { name: "San Martinas",       name_de: "San Martinas",       x: 1089, y: 1375, type: "n" },
  { name: "Tortuga",            name_de: "Tortuga",            x: 1129, y: 771,  type: "p" },
  { name: "La Navidad",         name_de: "La Navidad",         x: 1244, y: 918,  type: "n" },
  { name: "Thermopylae",        name_de: "Thermopylae",        x: 1260, y: 617,  type: "n" },
  { name: "Aldansk",            name_de: "Aldansk",            x: 1274, y: 133,  type: "f" },
  { name: "South Bastion",      name_de: "Südbastion",         x: 1297, y: 1287, type: "n" },
  { name: "Gray Island",        name_de: "Graue Insel",        x: 1343, y: 403,  type: "n" },
  { name: "St. Jean",           name_de: "St. Jean",           x: 1375, y: 1016, type: "f" },
  { name: "Fiji",               name_de: "Fiji",               x: 1454, y: 747,  type: "n" },
  { name: "Severoangelsk",      name_de: "Severoangelsk",      x: 1463, y: 140,  type: "n" },
  { name: "Bord Radel",         name_de: "Bord Radel",         x: 1528, y: 1400, type: "n" },
  { name: "North Bastion",      name_de: "Nordbastion",        x: 1553, y: 355,  type: "n" },
  { name: "Los Catuano",        name_de: "Los Catuano",        x: 1582, y: 1162, type: "n" },
  { name: "Brandport",          name_de: "Brandport",          x: 1641, y: 664,  type: "f" },
  { name: "Santa Maria",        name_de: "Santa Marta",        x: 1716, y: 1021, type: "f" },
  { name: "Northside",          name_de: "Nordseite",          x: 1718, y: 201,  type: "n" },
  { name: "Puerto Salada",      name_de: "Puerto Salada",      x: 1739, y: 1232, type: "n" },
  { name: "Freebooter Bay",     name_de: "Freibeuter-Bucht",   x: 1763, y: 835,  type: "p" },
  { name: "Freedom Bay",        name_de: "Freiheit-Bucht",     x: 1769, y: 508,  type: "f" }
];

const portZones = {
  "Assab": "Khalij Albaharad",
  "Cursed City": "Dragon Islands",
  "Al-Khalif": "Khalij Albaharad",
  "Nisogora": "Sea of Nozula",
  "Nordberg": "Sea of Nozula",
  "West Bastion": "Dragon Islands",
  "Sharhat": "Khalij Albaharad",
  "Oneg": "Sea of Nozula",
  "Naabad Stronghold": "Dragon Islands",
  "Gelbion": "Lagonav",
  "Masadora": "Dragon Islands",
  "Devios": "Lagrimas de Viudas",
  "El Tigre": "Lagrimas de Viudas",
  "Surako": "Lagonav",
  "Corsa-Nois Bay": "Friesland",
  "Bridgetown": "Heart of the Abyss",
  "San Cristobel": "Sea of Conqustadors",
  "Charleston": "Heart of the Abyss",
  "Nevis": "Heart of the Abyss",
  "Pirate City": "Sea of Conqustadors",
  "Everston": "Strait of a Thousand Dead Man",
  "Laguna Blanco": "Heart of the Abyss",
  "Aruba": "Strait of a Thousand Dead Man",
  "San Martinas": "Sea of Conqustadors",
  "Tortuga": "Heart of the Abyss",
  "La Navidad": "Danamar",
  "Thermopylae": "Heart of the Abyss",
  "Aldansk": "Strait of a Thousand Dead Man",
  "South Bastion": "Islas Dias Augado",
  "Gray Island": "Strait of a Thousand Dead Man",
  "St. Jean": "Danamar",
  "Fiji": "Casa Nuevo",
  "Severoangelsk": "Stevenson Islands",
  "Bord Radel": "Islas Dias Augado",
  "North Bastion": "Stevenson Islands",
  "Los Catuano": "Aurora Islands",
  "Brandport": "Antillean Islands",
  "Santa Maria": "Aurora Islands",
  "Northside": "Stevenson Islands",
  "Puerto Salada": "Aurora Islands",
  "Freebooter Bay": "Antillean Islands",
  "Freedom Bay": "Antillean Islands"
};

const portSearchAliases = {
  "Los Catuano": ["Los Catuona"],
  "San Cristobel": ["San Cristobal"],
  "St. Jean": ["St Jean", "Saint Jean", "St. John", "Saint John"],
  "Santa Maria": ["Santa Marta"],
  "Pirate City": ["Pirate town", "Piratenstadt"],
  "West Bastion": ["Westbastion"],
  "North Bastion": ["Nordbastion"]
};

const DEFAULT_ISLAND_WORKSHOPS = ['ws_plank', 'ws_weaving', 'ws_bronze', 'ws_plate', 'ws_bulkhead', 'ws_provision'];
const DEFAULT_ISLAND_PRODUCTIONS = ['prod_beer', 'prod_grain', 'prod_supplies', 'prod_sugar'];

const islandWorkshopOptionsByZone = {
  default: DEFAULT_ISLAND_WORKSHOPS,
  "Antillean Islands": DEFAULT_ISLAND_WORKSHOPS,
  "Aurora Islands": DEFAULT_ISLAND_WORKSHOPS,
  "Casa Nuevo": DEFAULT_ISLAND_WORKSHOPS,
  "Danamar": DEFAULT_ISLAND_WORKSHOPS,
  "Dragon Islands": DEFAULT_ISLAND_WORKSHOPS,
  "Friesland": DEFAULT_ISLAND_WORKSHOPS,
  "Heart of the Abyss": DEFAULT_ISLAND_WORKSHOPS,
  "Islas Dias Augado": DEFAULT_ISLAND_WORKSHOPS,
  "Khalij Albaharad": DEFAULT_ISLAND_WORKSHOPS,
  "Lagonav": DEFAULT_ISLAND_WORKSHOPS,
  "Lagrimas de Viudas": DEFAULT_ISLAND_WORKSHOPS,
  "Sea of Conqustadors": DEFAULT_ISLAND_WORKSHOPS,
  "Sea of Nozula": DEFAULT_ISLAND_WORKSHOPS,
  "Stevenson Islands": DEFAULT_ISLAND_WORKSHOPS,
  "Strait of a Thousand Dead Man": DEFAULT_ISLAND_WORKSHOPS
};

// Community-derived production options by zone. I could not verify a complete
// official island-production table online, so this mapping intentionally prefers
// broader option sets over overly restrictive dropdowns.
const islandProductionOptionsByZone = {
  default: DEFAULT_ISLAND_PRODUCTIONS,
  "Antillean Islands": DEFAULT_ISLAND_PRODUCTIONS,
  "Aurora Islands": DEFAULT_ISLAND_PRODUCTIONS,
  "Casa Nuevo": DEFAULT_ISLAND_PRODUCTIONS,
  "Danamar": DEFAULT_ISLAND_PRODUCTIONS,
  "Dragon Islands": DEFAULT_ISLAND_PRODUCTIONS,
  "Friesland": DEFAULT_ISLAND_PRODUCTIONS,
  "Heart of the Abyss": DEFAULT_ISLAND_PRODUCTIONS,
  "Islas Dias Augado": DEFAULT_ISLAND_PRODUCTIONS,
  "Khalij Albaharad": DEFAULT_ISLAND_PRODUCTIONS,
  "Lagonav": DEFAULT_ISLAND_PRODUCTIONS,
  "Lagrimas de Viudas": DEFAULT_ISLAND_PRODUCTIONS,
  "Sea of Conqustadors": DEFAULT_ISLAND_PRODUCTIONS,
  "Sea of Nozula": DEFAULT_ISLAND_PRODUCTIONS,
  "Stevenson Islands": DEFAULT_ISLAND_PRODUCTIONS,
  "Strait of a Thousand Dead Man": DEFAULT_ISLAND_PRODUCTIONS
};
// =============================================================================
// LIGHTHOUSE DATA
// =============================================================================
const lighthouses = [
  { x: 1237, y: 118 }, { x: 1325, y: 132 }, { x: 1407, y: 137 },
  { x: 405, y: 141 }, { x: 1507, y: 172 }, { x: 1280, y: 177 },
  { x: 274, y: 179 }, { x: 794, y: 183 }, { x: 331, y: 184 },
  { x: 1673, y: 185 }, { x: 1457, y: 195 }, { x: 925, y: 219 },
  { x: 1767, y: 250 }, { x: 194, y: 252 }, { x: 1701, y: 267 },
  { x: 889, y: 277 }, { x: 503, y: 289 }, { x: 1105, y: 321 },
  { x: 1035, y: 332 }, { x: 188, y: 333 }, { x: 250, y: 336 },
  { x: 1511, y: 343 }, { x: 1598, y: 348 }, { x: 537, y: 350 },
  { x: 1417, y: 388 }, { x: 488, y: 395 }, { x: 1591, y: 399 },
  { x: 1061, y: 401 }, { x: 1270, y: 402 }, { x: 209, y: 403 },
  { x: 1318, y: 449 }, { x: 1776, y: 465 }, { x: 126, y: 472 },
  { x: 202, y: 475 }, { x: 562, y: 479 }, { x: 827, y: 488 },
  { x: 1735, y: 507 }, { x: 602, y: 519 }, { x: 1769, y: 546 },
  { x: 1280, y: 567 }, { x: 874, y: 568 }, { x: 547, y: 570 },
  { x: 830, y: 592 }, { x: 137, y: 594 }, { x: 61, y: 598 },
  { x: 1205, y: 612 }, { x: 1627, y: 625 }, { x: 1231, y: 663 },
  { x: 1612, y: 689 }, { x: 105, y: 690 }, { x: 1656, y: 691 },
  { x: 1421, y: 715 }, { x: 1519, y: 719 }, { x: 188, y: 769 },
  { x: 465, y: 786 }, { x: 1444, y: 804 }, { x: 547, y: 805 },
  { x: 778, y: 808 }, { x: 268, y: 822 }, { x: 677, y: 843 },
  { x: 1243, y: 866 }, { x: 197, y: 869 }, { x: 527, y: 876 },
  { x: 1307, y: 883 }, { x: 744, y: 889 }, { x: 1172, y: 901 },
  { x: 950, y: 928 }, { x: 726, y: 944 }, { x: 1374, y: 975 },
  { x: 1028, y: 985 }, { x: 927, y: 993 }, { x: 1685, y: 997 },
  { x: 1754, y: 1002 }, { x: 811, y: 1010 }, { x: 1325, y: 1019 },
  { x: 730, y: 1031 }, { x: 286, y: 1060 }, { x: 1388, y: 1061 },
  { x: 1728, y: 1066 }, { x: 317, y: 1081 }, { x: 1604, y: 1105 },
  { x: 530, y: 1122 }, { x: 255, y: 1123 }, { x: 1528, y: 1138 },
  { x: 102, y: 1172 }, { x: 488, y: 1195 }, { x: 583, y: 1209 },
  { x: 1585, y: 1218 }, { x: 1777, y: 1230 }, { x: 1698, y: 1232 },
  { x: 141, y: 1233 }, { x: 1291, y: 1239 }, { x: 75, y: 1255 },
  { x: 1725, y: 1267 }, { x: 1340, y: 1287 }, { x: 716, y: 1288 },
  { x: 806, y: 1295 }, { x: 530, y: 1310 }, { x: 1277, y: 1320 },
  { x: 1067, y: 1325 }, { x: 119, y: 1339 }, { x: 600, y: 1345 },
  { x: 1129, y: 1350 }, { x: 809, y: 1351 }, { x: 64, y: 1361 },
  { x: 1507, y: 1364 }, { x: 1580, y: 1378 }, { x: 510, y: 1402 },
  { x: 1050, y: 1414 }, { x: 157, y: 1426 }, { x: 1555, y: 1435 }
];

// =============================================================================
// POI DATA
// =============================================================================
const pois = [
  // --- Personal Islands ---
  { type: "island", x: 67, y: 943, id: "#1" },
  { type: "island", x: 90, y: 1299, id: "#2" },
  { type: "island", x: 108, y: 281, id: "#3" },
  { type: "island", x: 170, y: 664, id: "#4" },
  { type: "island", x: 205, y: 1051, id: "#5" },
  { type: "island", x: 228, y: 189, id: "#6" },
  { type: "island", x: 250, y: 1281, id: "#7" },
  { type: "island", x: 286, y: 1185, id: "#8" },
  { type: "island", x: 293, y: 594, id: "#9" },
  { type: "island", x: 324, y: 1444, id: "#10" },
  { type: "island", x: 328, y: 358, id: "#11" },
  { type: "island", x: 354, y: 421, id: "#12" },
  { type: "island", x: 354, y: 992, id: "#13" },
  { type: "island", x: 368, y: 793, id: "#14" },
  { type: "island", x: 432, y: 1323, id: "#15" },
  { type: "island", x: 437, y: 486, id: "#16" },
  { type: "island", x: 441, y: 143, id: "#17" },
  { type: "island", x: 447, y: 1455, id: "#18" },
  { type: "island", x: 472, y: 903, id: "#19" },
  { type: "island", x: 485, y: 432, id: "#20" },
  { type: "island", x: 535, y: 737, id: "#21" },
  { type: "island", x: 567, y: 1281, id: "#22" },
  { type: "island", x: 576, y: 1103, id: "#23" },
  { type: "island", x: 580, y: 454, id: "#24" },
  { type: "island", x: 604, y: 420, id: "#25" },
  { type: "island", x: 638, y: 169, id: "#26" },
  { type: "island", x: 684, y: 661, id: "#27" },
  { type: "island", x: 684, y: 1032, id: "#28" },
  { type: "island", x: 714, y: 732, id: "#29" },
  { type: "island", x: 736, y: 231, id: "#30" },
  { type: "island", x: 738, y: 416, id: "#31" },
  { type: "island", x: 814, y: 1165, id: "#32" },
  { type: "island", x: 862, y: 1001, id: "#33" },
  { type: "island", x: 869, y: 118, id: "#34" },
  { type: "island", x: 887, y: 883, id: "#35" },
  { type: "island", x: 898, y: 1348, id: "#36" },
  { type: "island", x: 947, y: 487, id: "#37" },
  { type: "island", x: 1031, y: 1305, id: "#38" },
  { type: "island", x: 1086, y: 899, id: "#39" },
  { type: "island", x: 1382, y: 897, id: "#40" },  // moved: north of St. Jean (was in PvP H-4)
  { type: "island", x: 1108, y: 826, id: "#41" },
  { type: "island", x: 1126, y: 447, id: "#42" },
  { type: "island", x: 1132, y: 1108, id: "#43" },
  { type: "island", x: 1141, y: 999, id: "#44" },
  { type: "island", x: 1164, y: 313, id: "#45" },
  { type: "island", x: 1171, y: 1244, id: "#46" },
  { type: "island", x: 1218, y: 1451, id: "#47" },
  { type: "island", x: 1240, y: 782, id: "#48" },
  { type: "island", x: 1256, y: 1218, id: "#49" },
  { type: "island", x: 1304, y: 117, id: "#50" },
  { type: "island", x: 1320, y: 482, id: "#51" },
  { type: "island", x: 1347, y: 777, id: "#52" },
  { type: "island", x: 1354, y: 1416, id: "#53" },
  { type: "island", x: 1366, y: 341, id: "#54" },
  { type: "island", x: 1409, y: 1285, id: "#55" },
  { type: "island", x: 1433, y: 1059, id: "#56" },
  { type: "island", x: 1443, y: 535, id: "#58" },
  { type: "island", x: 1485, y: 1152, id: "#59" },
  { type: "island", x: 1488, y: 214, id: "#60" },
  { type: "island", x: 1510, y: 472, id: "#61" },
  { type: "island", x: 1579, y: 793, id: "#62" },
  { type: "island", x: 1612, y: 1448, id: "#63" },
  { type: "island", x: 1632, y: 327, id: "#64" },
  { type: "island", x: 1698, y: 593, id: "#65" },
  { type: "island", x: 1735, y: 1378, id: "#66" },
  { type: "island", x: 495, y: 629, id: "#162" },

  // --- Coal ---
  { type: "coal", x: 241, y: 1462, id: "#67" },
  { type: "coal", x: 342, y: 743, id: "#68" },
  { type: "coal", x: 733, y: 1251, id: "#69" },
  { type: "coal", x: 995, y: 651, id: "#70" },
  { type: "coal", x: 1021, y: 761, id: "#71" },
  { type: "coal", x: 1134, y: 954, id: "#72" },
  { type: "coal", x: 1274, y: 1212, id: "#73" },
  { type: "coal", x: 1653, y: 828, id: "#74" },

  // --- Copper ---
  { type: "copper", x: 820, y: 639, id: "#75" },
  { type: "copper", x: 974, y: 299, id: "#76" },
  { type: "copper", x: 1009, y: 858, id: "#77" },
  { type: "copper", x: 1223, y: 482, id: "#78" },

  // --- Farm ---
  { type: "farm", x: 290, y: 1280, id: "#79" },
  { type: "farm", x: 432, y: 905, id: "#80" },
  { type: "farm", x: 476, y: 522, id: "#81" },
  { type: "farm", x: 1070, y: 1092, id: "#82" },
  { type: "farm", x: 1357, y: 990, id: "#83" },
  { type: "farm", x: 1768, y: 1057, id: "#86", outsideMap: true },

  // --- Iron ---
  { type: "iron", x: 259, y: 260, id: "#87" },
  { type: "iron", x: 343, y: 1161, id: "#88" },
  { type: "iron", x: 583, y: 647, id: "#89" },
  { type: "iron", x: 883, y: 350, id: "#90" },
  { type: "iron", x: 963, y: 129, id: "#91" },
  { type: "iron", x: 1130, y: 614, id: "#92" },
  { type: "iron", x: 1246, y: 700, id: "#93" },
  { type: "iron", x: 1634, y: 251, id: "#94" },
  { type: "iron", x: 1658, y: 1434, id: "#95" },
  { type: "iron", x: 1721, y: 519, id: "#96" },

  // --- Resin ---
  { type: "resin", x: 274, y: 1045, id: "#97" },
  { type: "resin", x: 583, y: 1031, id: "#98" },
  { type: "resin", x: 1225, y: 1375, id: "#99" },
  { type: "resin", x: 1761, y: 1210, id: "#100", outsideMap: true },

  // --- Rum ---
  { type: "rum", x: 79, y: 512, id: "#101" },
  { type: "rum", x: 461, y: 726, id: "#102" },
  { type: "rum", x: 678, y: 362, id: "#103" },
  { type: "rum", x: 1452, y: 470, id: "#104" },
  { type: "rum", x: 1532, y: 716, id: "#105" },

  // --- Water ---
  { type: "water", x: 187, y: 194, id: "#106" },
  { type: "water", x: 510, y: 99, id: "#107" },
  { type: "water", x: 1355, y: 110, id: "#108" },
  { type: "water", x: 1596, y: 133, id: "#109" },
  { type: "water", x: 1770, y: 155, id: "#110" },
  { type: "water", x: 32, y: 179, id: "#123", outsideMap: true },
  { type: "water", x: 1072, y: 35, id: "#124", outsideMap: true },

  // --- Wood ---
  { type: "wood", x: 110, y: 942, id: "#111" },
  { type: "wood", x: 313, y: 422, id: "#112" },
  { type: "wood", x: 586, y: 1453, id: "#113" },
  { type: "wood", x: 633, y: 724, id: "#114" },
  { type: "wood", x: 645, y: 1186, id: "#115" },
  { type: "wood", x: 734, y: 530, id: "#116" },
  { type: "wood", x: 941, y: 1375, id: "#117" },
  { type: "wood", x: 1291, y: 869, id: "#118" },
  { type: "wood", x: 1363, y: 570, id: "#119" },
  { type: "wood", x: 1443, y: 1439, id: "#120" },
  { type: "wood", x: 1480, y: 889, id: "#121" },
  { type: "wood", x: 1723, y: 1357, id: "#122" },

  // --- Altars ---
  { type: "altar", x: 422, y: 709, id: "#125" },
  { type: "altar", x: 751, y: 1444, id: "#126" },
  { type: "altar", x: 843, y: 882, id: "#127" },
  { type: "altar", x: 1186, y: 545, id: "#128" },
  { type: "altar", x: 1834, y: 923, id: "#129", outsideMap: true },

  // --- Forts ---
  { type: "fort", x: 32, y: 543, id: "#130" },
  { type: "fort", x: 86, y: 1102, id: "#131" },
  { type: "fort", x: 129, y: 256, id: "#132" },
  { type: "fort", x: 229, y: 704, id: "#133" },
  { type: "fort", x: 277, y: 1234, id: "#134" },
  { type: "fort", x: 347, y: 497, id: "#135" },
  { type: "fort", x: 375, y: 318, id: "#136" },
  { type: "fort", x: 404, y: 1460, id: "#137" },
  { type: "fort", x: 419, y: 1001, id: "#138" },
  { type: "fort", x: 615, y: 795, id: "#139" },
  { type: "fort", x: 764, y: 35, id: "#140" },
  { type: "fort", x: 767, y: 271, id: "#141" },
  { type: "fort", x: 784, y: 1515, id: "#142" },
  { type: "fort", x: 795, y: 1078, id: "#143" },
  { type: "fort", x: 969, y: 1056, id: "#144" },
  { type: "fort", x: 1013, y: 723, id: "#145" },
  { type: "fort", x: 1053, y: 1244, id: "#146" },
  { type: "fort", x: 1144, y: 565, id: "#147" },
  { type: "fort", x: 1175, y: 248, id: "#148" },
  { type: "fort", x: 1242, y: 1140, id: "#149" },
  { type: "fort", x: 1282, y: 1441, id: "#150" },
  { type: "fort", x: 1297, y: 701, id: "#151" },
  { type: "fort", x: 1520, y: 560, id: "#152" },
  { type: "fort", x: 1623, y: 1263, id: "#153" },
  { type: "fort", x: 1665, y: 896, id: "#154" },
  { type: "fort", x: 1712, y: 310, id: "#155" },
  { type: "fort", x: 1811, y: 1094, id: "#156", outsideMap: true },
  { type: "fort", x: 1834, y: 1500, id: "#157", outsideMap: true },

  // --- Printshops ---
  { type: "printshop", x: 32, y: 439, id: "#158", outsideMap: true },
  { type: "printshop", x: 925, y: 1515, id: "#159", outsideMap: true },
  { type: "printshop", x: 1800, y: 1515, id: "#160", outsideMap: true },
  { type: "printshop", x: 1833, y: 345, id: "#161", outsideMap: true }
];

// =============================================================================
// FAST TRAVEL ROUTES (for animated polylines - Phase 14)
// Each route is an array of [x, y] waypoints between ports
// =============================================================================
const fastTravelRoutes = [
  { from: "Oneg", to: "Corsa-Nois Bay", points: [[341, 121], [672, 102]] },
  { from: "Corsa-Nois Bay", to: "Aldansk", points: [[672, 102], [1274, 133]] },
  { from: "Aldansk", to: "Severoangelsk", points: [[1274, 133], [1463, 140]] },
  { from: "Severoangelsk", to: "Northside", points: [[1463, 140], [1718, 201]] },
  { from: "Nordberg", to: "Gelbion", points: [[217, 301], [483, 342]] },
  { from: "Gelbion", to: "Surako", points: [[483, 342], [553, 529]] },
  { from: "Surako", to: "Nevis", points: [[553, 529], [826, 539]] },
  { from: "Nevis", to: "Aruba", points: [[826, 539], [1083, 354]] },
  { from: "Aruba", to: "Gray Island", points: [[1083, 354], [1343, 403]] },
  { from: "Gray Island", to: "North Bastion", points: [[1343, 403], [1553, 355]] },
  { from: "North Bastion", to: "Freedom Bay", points: [[1553, 355], [1769, 508]] },
  { from: "Cursed City", to: "Naabad Stronghold", points: [[101, 636], [403, 676]] },
  { from: "Naabad Stronghold", to: "Masadora", points: [[403, 676], [499, 829]] },
  { from: "Masadora", to: "Bridgetown", points: [[499, 829], [730, 836]] },
  { from: "Bridgetown", to: "Tortuga", points: [[730, 836], [1129, 771]] },
  { from: "Tortuga", to: "Thermopylae", points: [[1129, 771], [1260, 617]] },
  { from: "Thermopylae", to: "Fiji", points: [[1260, 617], [1454, 747]] },
  { from: "Fiji", to: "Brandport", points: [[1454, 747], [1641, 664]] },
  { from: "Brandport", to: "Freebooter Bay", points: [[1641, 664], [1763, 835]] },
  { from: "West Bastion", to: "Charleston", points: [[214, 818], [763, 986]] },
  { from: "Charleston", to: "Laguna Blanco", points: [[763, 986], [975, 969]] },
  { from: "Laguna Blanco", to: "La Navidad", points: [[975, 969], [1244, 918]] },
  { from: "La Navidad", to: "St. Jean", points: [[1244, 918], [1375, 1016]] },
  { from: "St. Jean", to: "Santa Maria", points: [[1375, 1016], [1716, 1021]] },
  { from: "Sharhat", to: "Devios", points: [[290, 1105], [540, 1177]] },
  { from: "Devios", to: "San Cristobel", points: [[540, 1177], [751, 1350]] },
  { from: "San Cristobel", to: "San Martinas", points: [[751, 1350], [1089, 1375]] },
  { from: "San Martinas", to: "South Bastion", points: [[1089, 1375], [1297, 1287]] },
  { from: "South Bastion", to: "Los Catuano", points: [[1297, 1287], [1582, 1162]] },
  { from: "Los Catuano", to: "Puerto Salada", points: [[1582, 1162], [1739, 1232]] },
  { from: "Al-Khalif", to: "El Tigre", points: [[110, 1393], [552, 1364]] },
  { from: "El Tigre", to: "Pirate City", points: [[552, 1364], [843, 1419]] },
  { from: "Pirate City", to: "Bord Radel", points: [[843, 1419], [1528, 1400]] },
  { from: "Everston", to: "Corsa-Nois Bay", points: [[867, 232], [672, 102]] },
  { from: "Northside", to: "Freedom Bay", points: [[1718, 201], [1769, 508]] },
  { from: "Freedom Bay", to: "Freebooter Bay", points: [[1769, 508], [1763, 835]] },
  { from: "Freebooter Bay", to: "Santa Maria", points: [[1763, 835], [1716, 1021]] },
  { from: "Santa Maria", to: "Puerto Salada", points: [[1716, 1021], [1739, 1232]] },
  { from: "Assab", to: "Al-Khalif", points: [[97, 1211], [110, 1393]] },
  { from: "Cursed City", to: "West Bastion", points: [[101, 636], [214, 818]] },
  { from: "West Bastion", to: "Sharhat", points: [[214, 818], [290, 1105]] },
  { from: "Sharhat", to: "Assab", points: [[290, 1105], [97, 1211]] },
  { from: "Nisogora", to: "Nordberg", points: [[166, 434], [217, 301]] },
  { from: "Nisogora", to: "Cursed City", points: [[166, 434], [101, 636]] },
];











